language: c

cache: apt


dist: trusty

dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_image hackrf; fi

script:
  - make

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libhackrf-dev
